let emptyArray = [];
let hobbies = ["coding","drawing","watching movies","swimming","going out","learning new techs"];
let numbers = [1,2,3,12,20];
console.log(numbers[1]);
console.log(hobbies[hobbies.length-1]);
hobbies.push("shopping");
console.log(hobbies[hobbies.length-1]);
console.log(hobbies.length);
hobbies.splice(-2);
console.log(hobbies.length);
console.log(hobbies);
hobbies = [];